article/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = "article"

urlpatterns = [
    path('article/<int:id>', detail, name='detail'),
    path('', articles, name='articles'),
    
]

kassa/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('articles/', include('article.urls')),
    path('about/', views.about, name='about'),
    path('refund/', views.refund, name='refund'),
    path('privacy/', views.privacy, name='privacy'),

    
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill

class Article(models.Model):
    author = models.ForeignKey('auth.user', on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    content = RichTextField(verbose_name="Содержание")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    article_image = ProcessedImageField(upload_to='blog_photos',
                                             processors=[ResizeToFill(360,300)],
                                             format='JPEG',
                                             options={'quality':60})
    article_image_thumbnail = ImageSpecField(source = 'article_image',
                                        processors=[ResizeToFill(360, 300)],
                                        format='JPEG',
                                        options={'quality': 60})
    #image_2 = models.ImageField(blank=True, null=True)

    category = models.CharField(max_length=50, null=True, blank=True)
    main_article = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

article/views.py
from django.shortcuts import render,  get_object_or_404, redirect
from .models import Article


def index(request):
    articles = Article.objects.filter(main_article=True)
    context = {"articles": articles}
    return render(request, 'index.html', context)

def articles(request):
    articles = Article.objects.all()
    context = {"articles": articles}
    return render(request, 'articles.html', context)

def about(request):
    return render(request, 'about_us.html')

def detail(request, id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article, id=id)
    context = {"article": article}
    return render(request, 'detail.html', context)

def refund(request):
    return render(request, 'refund.html')

def privacy(request):
    return render(request, 'privacy.html')

templates/about_us.html
{% extends "layout.html" %}
{% block title %} | О нас{% endblock %}
{% block body%}

<div class="container">
    <div  style="background-color: #f3f5f7;">
        <h3 style="margin-top:50px; text-align:center; margin-bottom:50px;"><br>Как мы работаем</h3>
        <div style = "margin-bottom:50px; padding-left: 60px; padding-right: 60px; font-size:20px; font-family:sans-serif;">


            <p style="line-height:30px; margin-top:40px;"><b>Tezbilet.kg не занимается продажей авиабилетов.</b> Наша основная задача - помочь вам найти лучшее из того, что предлагают наши надежные партнеры по всему миру. Сам процесс покупки происходит на веб-сайте нашего партнера, чье предложение вам больше всего понравится.</p>
            <p>Tezbilet.ru не делает наценок и не берет комиссии и вознаграждения со своих пользователей. Свои комиссионные мы получаем, непосредственно, от наших партнеров, за то, что привлекаем клиентов на их веб-сайты.</p>
            <p>Мы сотрудничаем с огромным количеством агентств по всему миру и можем предложить широкий спектр маршрутов, различных акций и скидок. Прямая связь с авиакомпаниями и агентствами позволяет нам моментально обновлять тарифы и специальные предложения.</p>
            <p>Наши партнеры – это компании с высокой репутацией, доказавшие свою надежность и высокий профессионализм. Мы очень ценим доверие наших клиентов, без которого невозможен наш собственный рост. Поэтому, мы всегда тщательно отбираем компании, с которыми заключаем партнерство.</p>
            <p><b>Если у вас имеются вопросы по поводу приобретенных авиабилетов</b> или нужно внести какие-то изменения (сдать/обменять), рекомендуем обратиться к представителям компании, у которой был заказан билет.</p>
            <br><br><br>

            <h2 style="text-align:center; font-size:40px; color: #1b1b1b; margin-top:40px;">Почему клиенты выбирают нас?</h2><br><br>
            <div class="row row-cols-1 row-cols-md-2 g-4">
              <div class="col">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Огромный выбор</h5>
                    <p class="card-text">Tezbilet сравнивает тысячи предложений от 725 авикомпаний мира, 45 агентств и 5 систем бронирования.</p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card">

                  <div class="card-body">
                    <h5 class="card-title">Надежный и бесплатный поиск</h5>
                    <p class="card-text">При выборе авиарейса, мы бесплатно направляем вас, к нашим проверенным партнёрам, которые продают билеты.</p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card">

                  <div class="card-body">
                    <h5 class="card-title">Онлайн-покупка авиабилетов — быстро и просто</h5>
                    <p class="card-text">У нас вы можете в пару кликов забронировать авиабилеты.</p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Никаких сборов или наценок</h5>
                    <p class="card-text">Цена, которую вы видите в результатах поисках именно та, которую вы будете платить.</p>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/articles.html
{% extends 'layout.html' %}
{% block body %}

    <div class="container">
        <header  class="py-5 bg-primary border-bottom mb-4">
            <div  class="container">
                <div class="text-center my-5">
                    <h1 style="color:white;" class="fw-bolder">Добро пожаловать на главную страницу блога!</h1>
                    <p style="color:white; font-weight: bold;" class="lead mb-0">Все интересные статьи и факты здесь</p>
                </div>
            </div>
        </header>
    </div>

<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% if articles %}
            {% for article in articles %}
                <div class="card">
                <div class="article__thumbnail article__item">
                  <a style="center" href="{% url 'article:detail' article.id %}"><img class="article__thumbnail__img" src="{{ article.article_image_thumbnail.url }}"/></a>
                </div>

                    <div class="card-body">
                        <a href="/articles/article/{{ article.id }}"><h5 class="card-title">{{ article.title }}</h5></a>
                        <p class="card-text">{{  article.content|safe|truncatewords:10  }}</p>
                    </div>
                    <div class="card-body d-flex flex-column">
                        <a style="center" href="{% url 'article:detail' article.id %}" class="btn btn-primary">Читать далее</a>
                    </div>
                </div>
        {% endfor %}
        {% else %}
        <div class="col-md-10 offset-md-3">
                    <div class="col-lg-8">
                        <div class="aler alert-danger">Пока нет статей</div>
                    </div>
                </div>
        {% endif %}
        </center>
    </div>
</div>


                
{% endblock %}

templates/detail.html
{% extends 'layout.html' %}
{% block title %} | {{ article.title }} {% endblock %}
{% block body %}

    <div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
        <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{ article.title }}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Опубликовано {{article.created_date}} автором {{article.author.username}}</div>
                    <!-- Post categories-->
                    <!--- <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a> --->
                </header>
                <!-- Preview image figure-->
                {% if article.article_image %}
                    <figure class="mb-4"><img class="img-fluid rounded" src="{{ article.article_image.url }}" style="width:100%;height:100%;" alt="..." /></figure>
                <!-- Post content-->
                {% else %}
                {% endif %}
                <section class="mb-5">
                    {{article.content | safe}}
                </section>
            </article>
            <div class="sharethis-inline-share-buttons"></div>
            <hr>

    </div>
</div>
    

{% endblock %}

templates/includes/footer.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<footer class = "bg-dark text-white pt-5 pb-4">
    <div class="container text-center text-md-left">

        <div class="row text-center text-md-left">

            <div class='col-md-3 col-lg-3 col-xl-3 mx-auto mt-3'>
                <h5 class="text-uppercase mb-4 font-weight-bold text-warning">О нас</h5>
                <p>Тез Билет — крупнейший поисковик авиабилетов в Кыргызстане. Мы сравниваем все доступные варианты перелётов по вашему запросу, а потом направляем вас для покупки на официальные сайты авиакомпаний и агентств.
                    Стоимость авиабилета, которую вы видите на Тез Билет — финальная. Мы убрали все скрытые услуги и галочки.</p>
            </div>

            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-warning"> Сервисы</h5>
                <p>
                    <a href="https://c24.travelpayouts.com/click?shmarker=120716&promo_id=519&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Страхование</a>
                </p>

                <p>
                    <a href="https://c102.travelpayouts.com/click?shmarker=120716&promo_id=2958&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Сим карты</a>
                </p>

                <p>
                    <a href="https://c10.travelpayouts.com/click?shmarker=120716.120716&promo_id=2022&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Прокат авто</a>
                </p>

                <p>
                    <a href="https://c57.travelpayouts.com/click?shmarker=120716.120716&promo_id=1669&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Прокат велосипедов</a>
                </p>

                <p>
                    <a href="https://c86.travelpayouts.com/click?shmarker=120716.120716&promo_id=2103&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Юридическая помощь</a>
                </p>

            </div>


            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Туры</h5>
                <p>
                    <a href="https://kruiz-online.tp.st/UzfsTOEA" class="text-white" style="text-decoration:none;">Морские круизы</a>
                </p>

                <p>
                    <a href="https://c140.travelpayouts.com/click?shmarker=120716.120716&promo_id=4338&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Пакет туры</a>
                </p>

                <p>
                    <a href="https://tp.media/r?marker=120716.120716&trs=36605&p=654&u=https%3A%2F%2Fweatlas.com%2F" class="text-white" style="text-decoration:none;">Экскурсии</a>
                </p>

                <p>
                    <a href="https://c140.travelpayouts.com/click?shmarker=120716.120716&promo_id=4338&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Свадебные туры</a>
                </p>

                <p>
                    <a href="https://c140.travelpayouts.com/click?shmarker=120716.120716&promo_id=4338&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Туры в Анталью</a>
                </p>

                <p>
                    <a href="https://c140.travelpayouts.com/click?shmarker=120716.120716&promo_id=4338&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Туры в ОАЭ</a>
                </p>

                <p>
                    <a href="https://c22.travelpayouts.com/click?shmarker=120716.120716&promo_id=201&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Трансферы</a>
                </p>

            </div>

            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Контакты</h5>
                <!---<p>
                    <i class="fas fa-home mr-3"></i>ул. К. Датка 597, г.Ош
                </p> --->

                <p>
                    <i class="fas fa-envelope mr-3"></i>tezbilet@gmail.com
                </p>

                <p>
                    <i class="fas fa-phone mr-3"></i>+996 755 05 75 01
                </p>
                <hr>
                <p>

                    <a href="{% url 'privacy' %}" class="mb-4 font-weight-bold text-warning" style="text-decoration:none;">Правила</a>
                </p>

                <p>
                    <a href="{% url 'refund'  %}" class="mb-4 font-weight-bold text-warning" style="text-decoration:none;">Возврат авиабилетов</a>
                </p>

            </div>

        </div>

        <hr class="mb-4">

        <div class="row align-items-center">
            <div class="col-md-7 col-lg-8">
                <p> Copyright 2020 All rights reserved by:
                    <a href="http://www.vadisoft.kg/" style="text-decoration:none;">
                        <strong class="text-warning">Vadi Soft</strong>
                    </a>
                </p>
            </div>


            <div class="col-md-5 col-lg-4">
                <div class="text-center text-md-right">
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item">
                            <a class="nav-link active" aria-current="page" href="https://www.facebook.com/profile.php?id=61552787621121"><i class="bi bi-facebook"></i></a>
                        </li>

                    
                        <li class="list-inline-item">
                            <a class="nav-link active" aria-current="page" href="https://c135.travelpayouts.com/click?shmarker=120716.120716&promo_id=4070&source_type=link&type=click&trs=36605"><i class="bi bi-instagram"></i></a>
                        </li>

                        <li class="list-inline-item">
                            <a class="nav-link active" aria-current="page" href="https://play.google.com/store/apps/details?id=ru.air.tezbilet&pli=1"><i class="bi bi-google-play"></i></a>
                        </li>

                        <!--- <li class="list-inline-item">
                            <a class="nav-link active" aria-current="page" href="https://play.google.com/store/apps/details?id=ru.air.tezbilet&pli=1"><i class="bi bi-whatsapp"></i></a>
                        </li>

                        <li class="list-inline-item">
                            <a class="nav-link active" aria-current="page" href="https://play.google.com/store/apps/details?id=ru.air.tezbilet&pli=1"><i class="bi bi-telegram"></i></a>
                        </li> --->


                    </ul>
                </div>
        </div>
    </div>
    </div>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">

  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">Главная</i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'about' %}">О нас</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'article:articles' %}">Блог</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="https://c135.travelpayouts.com/click?shmarker=120716.120716&promo_id=4070&source_type=link&type=click&trs=36605">ЖД Билеты</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">

        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="https://www.facebook.com/profile.php?id=61552787621121"><i class="bi bi-facebook"></i></a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="https://www.instagram.com/tezbilet_kg/"><i class="bi bi-instagram"></i></a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="https://play.google.com/store/apps/details?id=ru.air.tezbilet&pli=1"><i class="bi bi-google-play"></i></a>
        </li>

        <!--- <li class="list-inline-item">
            <a class="nav-link active" aria-current="page" href="https://play.google.com/store/apps/details?id=ru.air.tezbilet&pli=1"><i class="bi bi-whatsapp"></i></a>
        </li>

        <li class="list-inline-item">
            <a class="nav-link active" aria-current="page" href="https://web.telegram.org/@Akhmedov_124"><i class="bi bi-telegram"></i></a>
        </li> --->

      </ul>
    </div>
  </div>
</nav>

templates/index.html
{% extends 'layout.html' %}
{% block body %}

    <div class="container">
    <br><h1 style="color:red;" class="fw-bolder"><center>Поиск дешёвых авиабилетов</center></h1><br><br>
        <p>
            <script async src="https://tp.media/content?currency=kgs&trs=36605&shmarker=120716&show_hotels=false&powered_by=false&locale=ru&searchUrl=avia.tezbilet.kg%2Fflights&primary_override=%2332a8dd&color_button=%2332a8dd&color_icons=%2332a8dd&dark=%23262626&light=%23FFFFFF&secondary=%23FFFFFF&special=%23C4C4C4&color_focused=%2332a8dd&border_radius=0&no_labels=&plain=true&promo_id=7879&campaign_id=100" charset="utf-8"></script>
        </p><br><br><br>
    
        <div class="text-center my-5">
            <h2 class="fw-bolder">Интересные Статьи и Факты </h2>
        </div>
    </div>



<div class="container">
    <section id="article">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% if articles %}
            {% for article in articles %}
                <div class="card">
                    <div class="article__thumbnail article__item">
                        <a style="center" href="{% url 'article:detail' article.id %}"><img class="article__thumbnail__img" src="{{ article.article_image_thumbnail.url }}"/></a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <p class="card-text">{{  article.content|safe|truncatewords:10  }}</p>
                    </div>
                    <div class="card-body d-flex flex-column">
                            <a style="center" href="{% url 'article:detail' article.id %}" class="btn btn-primary">Читать далее</a>
                        </div>
                </div>
        {% endfor %}
        {% else %}
            <div class="col-md-10 offset-md-3">
                    <div class="col-lg-8">
                        <div class="aler alert-danger">Пока нет статей</div>
                    </div>
                </div>
        {% endif %}
            </center>
    </div>
    </section>
</div>
    
    
 {% endblock %}





        

templates/layout.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=6608702bcf805b001a79ee67&product=inline-share-buttons&source=platform" async="async"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>Тезбилет{% block title %} {% endblock %}</title>
</head>
<body>
    {% include 'includes/navbar.html' %}
    
    <br>
    <div class="container-fluid">
        {% block body %}
        {% endblock %}
    
    </div>

    {% include 'includes/footer.html' %}
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>

</html>

templates/refund.html
{% extends 'layout.html' %}
{% block title %} | Политика возврата {% endblock %}
{% block body %}
<div class="container">
    <div  style="background-color: #f3f5f7;">
        <h3 style="margin-top:50px; text-align:center; margin-bottom:50px;">Возврат авиабилетов</h3>
        <div style = "margin-bottom:50px; padding-left: 120px; padding-right: 120px; font-size:20px; font-family:sans-serif;">
            <p style="line-height:30px; margin-top:40px;">Tezbilet.kg не продаёт билеты, а ищет где их купить дешевле. Бронированием и продажей авиабилетов занимаются наши партнеры.</p>
            <p>Для того, чтобы сделать возврат авиабилета или его перебронировать, Вам
                необходимо связаться с агентством, у которого Вы заказали авиаперелёт.</p>
            <p>Найдите агента, у которого бронировали билет и созвонитесь с ним.
                Назовите имя и фамилию, даты маршрута и направление. Оператор найдет
                вашу бронь и поможет решить Вашу задачу.</p>
        </div>
    </div>
</div>

{% endblock %}

templates/zapas.html
{% extends 'layout.html' %}
{% block body %}

    <div class="container">
        <header  class="py-5 bg-primary border-bottom mb-4">
            <div  class="container">
                <div class="text-center my-5">
                    <h1 style="color:white;" class="fw-bolder">Добро пожаловать на главную страницу блога!</h1>
                    <p style="color:white; font-weight: bold;" class="lead mb-0">Все интересные статьи и факты здесь</p>
                </div>
            </div>
        </header>
    </div>


    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% if articles %}
            {% for article in articles %}
                <div class="card">
                <div class="article__thumbnail article__item">
                  <img class="article__thumbnail__img" src="{{ article.article_image_thumbnail.url }}"/>
                </div>

                    <div class="card-body">
                        <a href="/articles/article/{{ article.id }}"><h5 class="card-title">{{ article.title }}</h5></a>
                        <p class="card-text">{{  article.content|safe|truncatewords:10  }}</p>
                    </div>
                    <div class="card-body d-flex flex-column">
                        <a style="center" href="{% url 'article:detail' article.id %}" class="btn btn-primary">Читать далее</a>
                    </div>
                </div>
        {% endfor %}
        {% else %}
        <div class="col-md-10 offset-md-3">
                    <div class="col-lg-8">
                        <div class="aler alert-danger">Пока нет статей</div>
                    </div>
                </div>
        {% endif %}
        </center>
    </div>


                
{% endblock %}